apiVersion: v1
kind: ConfigMap
metadata:
  name: cacheproxyfy-config
  namespace: cacheproxyfy
data:
  CACHEPROXYFY_PROXY_PORT: "8080"
  CACHEPROXYFY_PROXY_ECOSYSTEMS: "npm,pypi,maven"

  CACHEPROXYFY_DATABASE_HOST: postgres
  CACHEPROXYFY_DATABASE_PORT: "5432"
  CACHEPROXYFY_DATABASE_USER: cacheproxyfy
  CACHEPROXYFY_DATABASE_DBNAME: cacheproxyfy
  CACHEPROXYFY_DATABASE_SSLMODE: disable

  CACHEPROXYFY_REDIS_ADDR: redis:6379
  CACHEPROXYFY_REDIS_DB: "0"

  CACHEPROXYFY_CACHE_BACKEND: local
  CACHEPROXYFY_CACHE_LOCAL_DIR: /app/data/artifacts
  CACHEPROXYFY_CACHE_TTL_HOURS: "720"
  CACHEPROXYFY_CACHE_EVICTION_INTERVAL_HOURS: "1"

  CACHEPROXYFY_SECURITY_CVE_SCANNING: "false"
  CACHEPROXYFY_SECURITY_BLOCK_SEVERITY: CRITICAL
  CACHEPROXYFY_SECURITY_WARN_SEVERITY: HIGH
